[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "serverless-http",
    "yt-dlp-wrap",
    "cors"
  ]
  included_files = ["functions/**/*"]

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.13.1"  # Especificamos la versión de Python

[build.processing]
  skip_processing = true