[build]
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "ytdl-core", "cors", "@distube/ytdl-core"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[dev]
  port = 8888

# Configuración específica para esbuild
[build.environment]
  NODE_VERSION = "18"