[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "serverless-http",
    "ytdl-core",
    "cors"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true