[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "serverless-http",
    "ytdl-core",
    "cors",
    "@distube/ytdl-core"
  ]
  included_files = ["functions/**/*"]

[build.environment]
  NODE_VERSION = "18"

# Redirecciones específicas para la API
[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Headers para CORS
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Origin, Content-Type, Accept"